stage:
  - build
  - test

building:
  stage: build
  script:
    - echo "Construir imagen..."
    - mkdir target1
    - touch api.jar
  artifacts:
    path:
      - target1/

testing:
  stage: test
  script:
    - echo "Testing..."
    - test -f "target1/api.jar"